#!/bin/bash

#date 20180710
#Funtion make a new job folder.Using the python suppoert to creat the artwork.
#By Simon Chen at bafelem@gmail.com

# Color
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
plain='\033[0m'

time_compare(){
	d=`date '+%H'`
	if [ $d -lt 7 ]; then
		echo `date -v-1d +%m%d`
	else
		echo `date '+%m%d'`
	fi
}
clear
k=$(time_compare)

job1=$1
test -z $1 && read -p "Please input your job number:" job1
echo -e "Initiating the files, please wait. ${red}DO NOT TYPE DURING THIS PERIOD.${plain}"
test -d ~/Documents/build/draft_artwork_folder/nn做稿 && rm -r ~/Documents/build/draft_artwork_folder/nn做稿
cp -r ~/Documents/build/draft_artwork_folder/n做稿 ~/Documents/build/draft_artwork_folder/nn做稿
cd ~/Documents/build/draft_artwork_folder/nn做稿
excel_path="$(pwd)/_DetailList_W.xlsx"

recl_full.py $job1 $excel_path

mv ~/Documents/build/draft_artwork_folder/nn做稿 ~/Documents/build/draft_artwork_folder/${job1}
cd ~/Documents/build/draft_artwork_folder/${job1}
d="_DetailList_W"
mv '_DetailList_W.xlsx' ${job1}${d}.xlsx
mkdir ./"1 intake sheet & order"/${k}
mkdir ./"2 raw client files"/${k}
cp -r ~/Documents/build/draft_artwork_folder/${job1} ~/Desktop/$job1' 做稿'
rm -r ~/Documents/build/draft_artwork_folder/${job1}
exit 0